### ISSUE TITLE
integrity:check-app returns "Certificate is not valid" with 20.0.8

### ISSUE THREAD

**Issue by aresius** [mwalbeck/nextcloud-breeze-dark#233]
**Describe the bug**
Since my update to Nextcloud 20.0.8 `occ integrity:check-app breezedark` returns
```
  - EXCEPTION:
    - class: OC\IntegrityCheck\Exceptions\InvalidSignatureException
    - message: Certificate is not valid.
```

I tried to remove and reinstall breeze-dark from customizations, but the result stays the same.

**Setup:**

-   Nextcloud version: 20.0.8
-   Theme version: 20.0.8
-   Browser and browser version: Chromium 88

Do I need to take some additional steps? Are they documented somewhere?

I could imagine this is related to #229

**Comment by theimperior** [comment]
I am having the same issue after the update to nc 20.0.8.

**Comment by mwalbeck** [comment]
Yes it is related to #229. I now realise I forgot to add the app cert as a secret on this GitHub repo, so the files are all signed as intended but the cert they should be verified against is missing. So this is purely an error on my part.

I'll go over the new bug reports as they are fairly simple issues and then I'll make a new release which should fix this before the end of the week. No further action is needed on your end.

I will also note that this signing process wasn't used in the app before. More specifically this signs all the files in tarball to help detect changes to files after the plugin has been installed. Before this release only the tarball as a whole was signed to be verified during installation.

**Comment by mwalbeck** [comment]
Going over the other issues went pretty quick so I've created a new release that fixes this issue. Thanks for reporting it.

Cheers!

**Comment by dkrainyk** [comment]
still getting: `Exception: App with id breezedark has invalid signature` when trying to install it on 21.0.0 Nextcloud

**Comment by mwalbeck** [comment]
@dkrainyk What's the app version?

**Comment by dkrainyk** [comment]
![image](https://user-images.githubusercontent.com/8302532/111391652-5b116000-86b5-11eb-919f-65713c1f3c78.png)
Breeze Dark is 21.0.4

**Comment by mwalbeck** [comment]
There was another issue with release information given to the app store for 21.0.4 that I think you might have gotten caught in. I have re-released 21.0.4 as 21.0.5 which should be good. Let me know if the signature issue persists after updating to 21.0.5.

**Comment by aresius** [comment]
20.0.9 works as expected and passes integrity:check-app at my Nextcloud 20.0.8 instance.

Thank you very much for the fast fix and in general for maintaining the nice theme.

**Comment by mwalbeck** [comment]
@aresius Thank you for letting me know and I'm glad you enjoy the theme.
