### ISSUE TITLE
App version showing some icons as black

### ISSUE THREAD

**Issue by CyberneticCody** [mwalbeck/nextcloud-breeze-dark#82]
Hello,
I just switched from the config version of this theme to the app version on the latest version of NextCloud (17.0.2) and I am having a small issue with the Icons on pages. After switching the icons turned black instead of white and in some instances are almost impossible to see.
![jhggyu](https://user-images.githubusercontent.com/55600371/73189601-abfd7800-40f2-11ea-9260-0cec765a914a.PNG)

Any help would be appreciated :) Thanks!

**Comment by mwalbeck** [comment]
Hi,

Have you tried to do a Ctrl + F5? If that doesn't work you can run **occ maintenance:repair** that will clear the css cache on the server and rebuild it. Just a heads up though, it may or may not leave your server without any css for a few minutes, which means it won't really be usable. That should fix it.

**Comment by CyberneticCody** [comment]
Looks like running **occ maintenance:repair** did the trick for most of the icons, cleared browser cache of course :)

The only icons that didn't fix are as seen in the images below.
(Apologies for the blue overlay, my screencap software hasn't been working since the last Linux release of the NVidia drivers...)
![Screenshot from 2020-01-27 16-59-46](https://user-images.githubusercontent.com/55600371/73217815-a6218a00-4126-11ea-81d8-822cb1efe58a.png)
![Screenshot from 2020-01-27 16-59-21](https://user-images.githubusercontent.com/55600371/73217816-a6218a00-4126-11ea-89fe-440e064b8697.png)

**Comment by mwalbeck** [comment]
That's good to hear.

I haven't seen the issue in Mail, but I also don't use on my own instance. I'm currently experiencing the same issue with files and I haven't found a root cause for it yet. On my development setup the issue has only been present in brief periods, which led me to believe it just was another caching issue, but I think there might be more at play here.

Icon variables from sass file are all merged into one icon-vars file, which means there is probably something taking precedent over my variable definition for those icons. I think it could be an app interfering in some way. If you wouldn't mind, could you share your list of apps installed on your server? It would help having a dataset bigger than one.

I have another idea of how to handle the icons that require a bit more work, but can be used for the troublesome icons, if it works.

**Comment by CyberneticCody** [comment]
My current list of active apps is as follows. It might be worth noting that after running `occ maintenance:repair` I tried disabling the theming app as well. That did not seem to help however...
I decided that it might also be worth restarting NGINX and PHP to clear their caches, but this didn't help. I also tried clearing my RAID's file cache as well, this also did not help.

There is nothing between my server and the open internet that would be caching after that other than the browser, and I have made sure to keep that cache off via developer tools when trying these things :)

I am running PHP 7.3 (FPM) with APC cache, NGINX 1.14.2 and Nextcloud 17.0.2 (I have not received the 18.0 update rollout yet)

I would like to add that I am very impressed with your theme, and my users love it as well :D
Thank you for your work!

```
Auditing / Logging  >  1.7.0

Breeze Dark  >  17.0.3

Brute-force settings  >  1.5.0

Calendar  >  2.0.1

Carnet  >  0.19.2

Comments  >  1.7.0

Contacts  >  3.1.8

Deleted files  >  1.7.0

Federation  >  1.7.0

File sharing  >  1.9.0

Group folders  >  5.0.5

Log Reader  >  2.2.0

Mail  >  1.1.1

Nextcloud announcements  >  1.6.0

Notifications  >  2.5.0

ONLYOFFICE  >  4.1.2

Passman  >  2.3.5

Password policy  >  1.7.0

PDF viewer  >  1.6.0

Share by mail  >  1.7.0

Text  >  1.1.1

Two-Factor TOTP Provider  >  4.1.2

Update notification  >  1.7.0

Video player  >  1.6.0

Viewer  >  1.2.0

```

**Comment by mwalbeck** [comment]
Thank you for the detailed report. That pretty much rules out caching completely for this issue. I've tried to see if I could find any connection between any apps that might cause this, but there doesn't seem to be any rhyme or reason to it. It just works on my development setup, but not on production, so I'm gonna put a pin in finding out why.

I have a fix that seems to work. It's basically just manually overriding icon definitions, so if you spot any other icons that have issues, please let me know. So far I've seen the issue in Files, Mail and Calendar.

Thank you for the kind words

**Comment by CyberneticCody** [comment]
I did find one more under /settings/user, the folder icon underneath the user's profile photo.
![sdfsdfsdfqweqwe](https://user-images.githubusercontent.com/55600371/73362847-9795b880-4275-11ea-84e0-93799b9ad94d.PNG)

>Thank you for the kind words

Of course! My users and I absolutely love this theme, especially being KDE users! I can tell a lot of work has gone into this, and I am actually pretty impressed. I know how much of a pain CSS can be...

**Comment by mwalbeck** [comment]
Great, I have included that in the patch and released a new version of the theme for both nc17 and nc18.

Hahah, I'm glad to hear it. It's nice to know people enjoy the theme.

**Comment by mwalbeck** [comment]
I forgot the favorites icon,

```
.nav-icon-favorites {
	background-image: var(--icon-star-dark-000);
}
```

**Comment by CyberneticCody** [comment]
The favorites icon did change to white after updating the theme to 17.0.4 for me

**Comment by CyberneticCody** [comment]
Edit: Just updated to NC 17.0.3 and the icon turned black after the update...

**Comment by mwalbeck** [comment]
Yeah, that is part of the problem and why I forgot it, because it works some of the time. There also isn't a clear indication of why it stops working, it just does...

**Comment by mwalbeck** [comment]
Okay, now it should be all good and fixed.
